---
label: produit
hide_body: false
is_partial: false
fields:
- type: text
  name: nom
  label: Nom
  default: Nom du produit
- type: text
  name: prix
  label: prix
  default: 100000FCFA
- type: textarea
  name: description
  label: Description
  default: Lorem Khaled Ipsum is a major key to success. Put it this way, it took
    me twenty five years to get these plants, twenty five years of blood sweat and
    tears, and I’m never giving up, I’m just getting started. It’s on you how you
    want to live your life. Everyone has a choice. I pick my choice, squeaky clean.
    Let’s see what Chef Dee got that they don’t want us to eat. Cloth talk. Mogul
    talk.
- type: file
  name: image
  label: image
  default: "/uploads/imgproduit.jpg"
pages:
- _produits/nom-du-produit.md
- _produits/nom-du-produit-1.md
- _produits/nom-du-produit-2.md
